# Site settings
title: Rachel V. Madrigal
email: rachelvmadrigal@gmail.com
description:
  Rachel's Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

collections:
  tagged:
    output: true
    permalink: /tagged/:path/
  education:
    output: true
    permalink: /education/:path/
  projects:
    output: true
    permalink: /projects/:path/
  work_experience:
    output: true
    permalink: /work_experience/:path/

# Build settings
markdown: kramdown
permalink: /entries/:year/:month/:day/:title
highlighter: rouge
